module.exports = {
    ERRORS: {
        // 课程管理错误
        ERR_COURSE_MAN_PERMISSION_DENIED: 'ERR_COURSE_MAN_PERMISSION_DENIED',
        ERR_MANAGER_AND_MEMBER_SAME: 'ERR_MANAGER_AND_MEMBER_SAME',

        // 提交信息不足
        ERR_NOT_ENOUGH_INFO: 'ERR_NOT_ENOUGH_INFO',

        // 设置用户信息出错
        ERR_WHEN_SET_USER_ID: 'ERR_WHEN_SET_USER_ID',
        ERR_WHEN_SET_USER_NAME: 'ERR_WHEN_SET_USER_NAME',

        // 设置课程信息出错
        ERR_COURSE_NAME: 'ERR_COURSE_NAME',
        ERR_COURSE_INFO: 'ERR_COURSE_INFO',
        ERR_INVALID_COURSE_ID: 'ERR_INVALID_COURSE_ID',

        // 签到时错误
        ERR_SIGNIN_OVER: "ERR_SIGNIN_OVER",
        ERR_SIGNIN_LOCATION: 'ERR_SIGNIN_LOCATION',
        ERR_SIGNIN_PIN: 'ERR_SIGNIN_PIN',

        // 权限问题 
        ERR_UNAUTHORIZED_OPERATION: 'ERR_UNAUTHORIZED_OPERATION',

        // detail?
        ERR_USER_NOT_FOUND: "ERR_USER_NOT_FOUND",
        ERR_COURSE_NOT_FOUND: "ERR_COURSE_NOT_FOUND",
        ERR_NOT_IN_THIS_COURSE: "ERR_NOT_IN_THIS_COURSE",
        ERR_BECOME_MANAGER: "ERR_BECOME_MANAGER",
        ERR_CORSE_SIGNING_IN: "ERR_CORSE_SIGNING_IN",

        ERR_NO_SIGNIN_RECORD: "ERR_NO_SIGNIN_RECORD",
        ERR_NO_SIGNIN_MEMBER: "ERR_NO_SIGNIN_MEMBER"
    }
}
